spring:
  application:
    name: profile-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.mayson.tech

server:
  port: 8083

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
